export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const GOOGLE_AUTH_ERROR = 'GOOGLE_AUTH_ERROR';
export const COOKIE_EXISTS = 'COOKIE_EXISTS';
export const NO_COOKIE = 'NO_COOKIE';
